"""Canonical IR: typed structured chunks + deterministic Markdown projection."""

from __future__ import annotations

from parsecraft.ir.markdown import render_block, render_page, to_markdown
from parsecraft.ir.models import (
    SCHEMA_VERSION,
    AssetKind,
    BBox,
    ChunkKind,
    ChunkRelation,
    CrossPageRelation,
    DetectedRegion,
    Diagnostic,
    DiagnosticLevel,
    DocumentMetadata,
    DocumentResult,
    ExtractedAsset,
    FailureCode,
    PageRange,
    PageResult,
    PageSignal,
    PassFailure,
    PassKind,
    PassStatus,
    QualitySignal,
    RegionKind,
    RelationKind,
    SourceSpan,
    StructuredChunk,
    TraceEntry,
    utcnow,
)

__all__ = [
    "SCHEMA_VERSION",
    "AssetKind",
    "BBox",
    "ChunkKind",
    "ChunkRelation",
    "CrossPageRelation",
    "DetectedRegion",
    "Diagnostic",
    "DiagnosticLevel",
    "DocumentMetadata",
    "DocumentResult",
    "ExtractedAsset",
    "FailureCode",
    "PageRange",
    "PageResult",
    "PageSignal",
    "PassFailure",
    "PassKind",
    "PassStatus",
    "QualitySignal",
    "RegionKind",
    "RelationKind",
    "SourceSpan",
    "StructuredChunk",
    "TraceEntry",
    "render_block",
    "render_page",
    "to_markdown",
    "utcnow",
]
